name: sam_rider_app
description: Flutter SAM Rider application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.0.3
  firebase_core: ^1.0.3
  firebase_auth: ^1.0.3
  firebase_database: ^6.1.2
  firebase_storage: ^8.0.3
  firebase_messaging: ^9.1.1
  cloud_firestore:  ^1.0.4
  shared_preferences: ^2.0.5 #0.5.3+4
  cached_network_image: ^3.0.0
  photo_view: ^0.11.1 #0.5.0
  http: ^0.13.1
#  google_maps_webservice: ^0.0.19
  location: ^4.1.1
  intro_slider: ^2.3.4
  flip_panel: ^1.0.1
#  google_map_location_picker: ^4.1.7
  image_picker: ^0.7.4
  fluttertoast: ^8.0.3
  cupertino_icons: ^0.1.3
  flutter_tags: ^0.4.9+1
  percent_indicator: ^3.0.1
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^0.21.0+1
  marquee: ^2.0.0
  credit_card_input_form: ^2.3.0
  native_pdf_view: ^4.0.1
  flutter_staggered_grid_view: ^0.3.4
  stripe_payment: ^1.1.1
  intl: ^0.17.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_map_location_picker:
    git: https://github.com/haleyhuynh/google_map_location_picker.git
  google_maps_webservice:
    git: https://github.com/haleyhuynh/google_maps_webservice.git

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/pdf/privacy.pdf
    - assets/pdf/termsofservice.pdf
    - assets/svg/
