name: sam_rider_app
description: Flutter SAM Rider application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.20+2
  firebase_auth: ^0.11.1+12
  firebase_database: ^3.0.5
  http: ^0.12.0+2
  google_maps_webservice: ^0.0.14
  location: ^3.0.0
  intro_slider: ^2.3.3

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
